#!/bin/bash
foreground=$1
background=$2
font=$3

pkill conky ; pkill dzen2 ; pkill tint2 ;

# Check to see if external is connected
if [[ -z `xrandr | grep " connected" | grep 'VGA'` ]]; then
  tint2 -c /home/bryan/.config/tint2/xmonad.tint2rc &
	conky -qc /home/bryan/.xmonad/.conky_dzen | dzen2 -x '1100' -w '700' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font & 
else 
	nitrogen --restore
	conky -qc /home/bryan/.xmonad/.conky_dzen | dzen2 -x '500' -w '1420' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font 
fi
